//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidDownload.WPF.Properties
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidDownload.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);
        internal static string LinkLabel => ResourceManager.GetString("LinkLabel", resourceCulture);
        internal static string PlaylistLinkLabel => ResourceManager.GetString("PlaylistLinkLabel", resourceCulture);
        internal static string BtnDownload => ResourceManager.GetString("BtnDownload", resourceCulture);
        internal static string BtnStop => ResourceManager.GetString("BtnStop", resourceCulture);
        internal static string BtnQueue => ResourceManager.GetString("BtnQueue", resourceCulture);
        internal static string BtnOpenFolder => ResourceManager.GetString("BtnOpenFolder", resourceCulture);
        internal static string BtnConverter => ResourceManager.GetString("BtnConverter", resourceCulture);
        internal static string BtnTheme => ResourceManager.GetString("BtnTheme", resourceCulture);
        internal static string BtnLang => ResourceManager.GetString("BtnLang", resourceCulture);
        internal static string LabelResolution => ResourceManager.GetString("LabelResolution", resourceCulture);
        internal static string LabelCodec => ResourceManager.GetString("LabelCodec", resourceCulture);
        internal static string LabelAudioFormat => ResourceManager.GetString("LabelAudioFormat", resourceCulture);
        internal static string LabelFormat => ResourceManager.GetString("LabelFormat", resourceCulture);
        internal static string CheckPlaylist => ResourceManager.GetString("CheckPlaylist", resourceCulture);
        internal static string CheckAudioOnly => ResourceManager.GetString("CheckAudioOnly", resourceCulture);
        internal static string CheckRecode => ResourceManager.GetString("CheckRecode", resourceCulture);
        internal static string MsgEmptyUrl => ResourceManager.GetString("MsgEmptyUrl", resourceCulture);
        internal static string MsgError => ResourceManager.GetString("MsgError", resourceCulture);
        internal static string MsgDownloadComplete => ResourceManager.GetString("MsgDownloadComplete", resourceCulture);
        internal static string MsgDownloadCancelled => ResourceManager.GetString("MsgDownloadCancelled", resourceCulture);
        internal static string MsgUpdateAvailable => ResourceManager.GetString("MsgUpdateAvailable", resourceCulture);
        internal static string MsgUpdateConfirm => ResourceManager.GetString("MsgUpdateConfirm", resourceCulture);
        internal static string MsgUpdateComplete => ResourceManager.GetString("MsgUpdateComplete", resourceCulture);
        internal static string MsgUpdateError => ResourceManager.GetString("MsgUpdateError", resourceCulture);
        internal static string MsgNoYtdlp => ResourceManager.GetString("MsgNoYtdlp", resourceCulture);
        internal static string MsgLanguageChanged => ResourceManager.GetString("MsgLanguageChanged", resourceCulture);
        internal static string QueueWindowTitle => ResourceManager.GetString("QueueWindowTitle", resourceCulture);
        internal static string QueueAddUrl => ResourceManager.GetString("QueueAddUrl", resourceCulture);
        internal static string QueueRemove => ResourceManager.GetString("QueueRemove", resourceCulture);
        internal static string QueueClear => ResourceManager.GetString("QueueClear", resourceCulture);
        internal static string QueueStartAll => ResourceManager.GetString("QueueStartAll", resourceCulture);
        internal static string QueueStop => ResourceManager.GetString("QueueStop", resourceCulture);
        internal static string QueueStatusWaiting => ResourceManager.GetString("QueueStatusWaiting", resourceCulture);
        internal static string QueueStatusDownloading => ResourceManager.GetString("QueueStatusDownloading", resourceCulture);
        internal static string QueueStatusDone => ResourceManager.GetString("QueueStatusDone", resourceCulture);
        internal static string QueueStatusCanceled => ResourceManager.GetString("QueueStatusCanceled", resourceCulture);
        internal static string QueueAllDone => ResourceManager.GetString("QueueAllDone", resourceCulture);
        internal static string QueueHasErrors => ResourceManager.GetString("QueueHasErrors", resourceCulture);
        internal static string QueueEmpty => ResourceManager.GetString("QueueEmpty", resourceCulture);
        internal static string QueueCount => ResourceManager.GetString("QueueCount", resourceCulture);
        internal static string HelpTitle => ResourceManager.GetString("HelpTitle", resourceCulture);
        internal static string ConvertWindowTitle => ResourceManager.GetString("ConvertWindowTitle", resourceCulture);
        internal static string BtnHelp => ResourceManager.GetString("BtnHelp", resourceCulture);
    }
}
